apiVersion: v1
kind: Service
metadata:
  name: aaa
  namespace: namespace-workflow-1746228705521
  labels:
    app.kubernetes.io/name: aaa
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aaa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80